timeout: 1200s

steps:
  # 1️⃣ Fetch secret from Secret Manager and save to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'FETCH_SECRET'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching GEMINI_API_KEY..."
        gcloud secrets versions access latest --secret="GEMINI_API_KEY" > /workspace/gemini_api_key.txt
        echo "Secret written to /workspace/gemini_api_key.txt"

  # 2️⃣ Build the Docker image (injecting GEMINI_API_KEY as a build arg)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'BUILD_IMAGE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        GEMINI_API_KEY=$(cat /workspace/gemini_api_key.txt)
        docker build \
          --build-arg GEMINI_API_KEY_ARG=$GEMINI_API_KEY \
          -t gcr.io/$PROJECT_ID/gemini-dj-app:latest .

  # 3️⃣ Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'PUSH_IMAGE'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-dj-app:latest']

  # 4️⃣ Deploy to Cloud Run with secrets + env vars
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'DEPLOY_RUN'
    args:
      [
        'run',
        'deploy',
        'deepj',
        '--image',
        'gcr.io/$PROJECT_ID/gemini-dj-app:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--set-secrets',
        'GEMINI_API_KEY=GEMINI_API_KEY:latest',
        '--set-env-vars',
        'FLASK_ENV=production,VERTEX_AI_LOCATION=us-central1,GEMINI_MODEL=gemini-1.5-pro-latest'
      ]

images:
  - 'gcr.io/$PROJECT_ID/gemini-dj-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY_SECRET