# 1. Fetch the secret from Secret Manager and write to a file
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'FETCH_SECRET'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Access the secret payload, base64 decode it, and save to a temporary file
        gcloud secrets versions access latest --secret="GEMINI_API_KEY" --format="get(payload.data)" | \
        tr '_-' '/+' | \
        base64 -d > /workspace/gemini_api_key.txt
    secretEnv: ['GEMINI_API_KEY_SECRET'] # Placeholder to ensure the builder has access

# 2. Build the Docker image, passing the key as a build argument
  - name: 'gcr.io/cloud-builders/docker'
    id: 'BUILD_IMAGE'
    args:
      [
        'build',
        '--build-arg',
        # Pass the key from the temporary file to the Dockerfile
        'GEMINI_API_KEY_ARG=$(cat /workspace/gemini_api_key.txt)',
        '-t',
        'gcr.io/$PROJECT_ID/gemini-dj-app:latest',
        '.',
      ]

# 3. Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'PUSH_IMAGE'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-dj-app:latest']

# 4. Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'DEPLOY_RUN'
    args:
      [
        'run',
        'deploy',
        'deepj',
        '--image',
        'gcr.io/$PROJECT_ID/gemini-dj-app:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

images:
  - 'gcr.io/$PROJECT_ID/gemini-dj-app:latest'

# Bind the secret to the build process so gcloud can fetch it
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
    env: GEMINI_API_KEY_SECRET # This is a placeholder and not used to expose the key