# cloudbuild.yaml
timeout: 1200s

steps:
  # 1. Fetch the secret from Secret Manager and write to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'FETCH_SECRET'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching secret from Secret Manager..."
        gcloud secrets versions access latest --secret="GEMINI_API_KEY" --format="get(payload.data)" | \
        tr '_-' '/+' | base64 -d > /workspace/gemini_api_key.txt
        echo "Secret written to /workspace/gemini_api_key.txt"

  # 2. Build Docker image with the key
  - name: 'gcr.io/cloud-builders/docker'
    id: 'BUILD_IMAGE'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        GEMINI_KEY=$(cat /workspace/gemini_api_key.txt)
        docker build \
          --build-arg GEMINI_API_KEY_ARG=$GEMINI_KEY \
          -t gcr.io/$PROJECT_ID/gemini-dj-app:latest .

  # 3. Push image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'PUSH_IMAGE'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-dj-app:latest']

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'DEPLOY_RUN'
    args:
      [
        'run', 'deploy', 'deepj',
        '--image', 'gcr.io/$PROJECT_ID/gemini-dj-app:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/gemini-dj-app:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY_SECRET